title: Settings
data:
  site_name: 'Davor Minchorov'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/davorminchorov'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/davorminchorov'
      icon: site/social-icons/github.svg
    -
      name: LinkedIn
      url: 'https://linkedin.com/in/davorminchorov'
      icon: site/social-icons/linkedin.svg
    -
      name: Email
      url: 'mailto:davorminchorov@gmail.com'
      icon: site/social-icons/email.svg
